# Generated by Django 5.2.4 on 2025-08-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usuariopersonalizado',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='username',
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuariopersonalizado',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
